---
language: node_js
node_js:
  - "stable"

sudo: required
dist: trusty

cache:
  directories:
    - node_modules

before_install:
  - npm install -g npm@^3
  - npm config set progress false
  - "phantomjs --version"

install:
  - npm install -g broccoli-cli
  - npm install

script:
  - npm run test:ci

env:
  - SAUCE_USERNAME=mobiledoc-kit SAUCE_ACCESS_KEY=f9cad21d-1141-452d-8f64-c6ba3f43faa6
