---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable
  firefox: "latest"
  sauce_connect:
    username: "mobiledoc-kit"
    access_key: "f9cad21d-1141-452d-8f64-c6ba3f43faa6"

env:
  - MOZ_HEADLESS=1 # necessary for Firefox headless, see https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-the-Firefox-addon-in-headless-mode

cache:
  yarn: true

script:
  - yarn test:ci
