---
language: node_js
node_js:
  - "6"

sudo: required
dist: trusty

addons:
  chrome: stable
  sauce_connect:
    username: mobiledoc-kit
    access_key: f9cad21d-1141-452d-8f64-c6ba3f43faa6

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --no-lockfile --non-interactive

script:
  - yarn test:ci
