name: Node.js CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn install
    - name: Run headless test
      uses: GabrielBB/xvfb-action@v1
      with:
        run: yarn test
